USE [master]
GO

/****** Object:  Database [CoffeeVendingMachine]    Script Date: 15/06/2026 12:31:27 ******/
CREATE DATABASE [CoffeeVendingMachine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoffeeVendingMachine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\CoffeeVendingMachine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoffeeVendingMachine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\CoffeeVendingMachine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoffeeVendingMachine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoffeeVendingMachine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoffeeVendingMachine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoffeeVendingMachine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoffeeVendingMachine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoffeeVendingMachine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET RECOVERY FULL 
GO

ALTER DATABASE [CoffeeVendingMachine] SET  MULTI_USER 
GO

ALTER DATABASE [CoffeeVendingMachine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoffeeVendingMachine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoffeeVendingMachine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoffeeVendingMachine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoffeeVendingMachine] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [CoffeeVendingMachine] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CoffeeVendingMachine] SET QUERY_STORE = ON
GO

ALTER DATABASE [CoffeeVendingMachine] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CoffeeVendingMachine] SET  READ_WRITE 
GO


